Задание 3: Проработка мира и монстров
PinochetLab/RoguelikeGame pull request #15
Opened 2023-06-11 19:34 UTC by EnergyNick

2023-06-17 11:34 UTC, yurii-litvinov requested changes

2023-06-17 11:34 UTC, yurii-litvinov commented on Roguelike/World/DefaultWorldBuilder.cs
> +                    component.CreateActor<Froggy>(x ,y);
```suggestion
                    component.CreateActor<Froggy>(x, y);
```
И ниже

2023-06-17 11:34 UTC, yurii-litvinov commented on Roguelike/World/IWorldBuilder.cs
> +    // IWorldBuilder SetupEnemies(IEnemiesProvider provider);
Закомментированный код не нужен

2023-06-17 11:34 UTC, yurii-litvinov commented on Roguelike/World/Providers/Generator/Dungeons/CellHelpers.cs
> +        }
Тут было бы вдвое короче со [switch expression](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/switch-expression)

2023-06-17 11:34 UTC, yurii-litvinov commented on Roguelike/World/Providers/Generator/Dungeons/CellHelpers.cs
> +        Iterate(template, (loc, tile) => map[x*cs + loc.X, y*cs + loc.Y] = tile);
```suggestion
        Iterate(template, (loc, tile) => map[x * cs + loc.X, y * cs + loc.Y] = tile);
```

2023-06-17 11:34 UTC, yurii-litvinov commented on Roguelike/World/Providers/Generator/Dungeons/CellHelpers.cs
> +            template[w/2, h/2].Attributes = AttributeType.Entry;
Тоже какая-то беда со стайлгайдом, и вообще как будто на C написано :) И в стандартной библиотеке вроде есть более высокоуровневые штуки для работы с флагами (сходу нагуглилось BitVector32, но у меня есть смутные воспоминания про более продвинутые штуки).

2023-06-17 11:34 UTC, yurii-litvinov commented on Roguelike/World/Providers/Generator/Dungeons/CellHelpers.cs
> +            }
Копипаст, кажется изживаемый

2023-06-17 11:34 UTC, yurii-litvinov commented on Roguelike/World/Providers/Generator/Dungeons/CellHelpers.cs
> +        for (var y = 0; y < template.GetLength(1); y++)
А тут бы отступ

2023-06-25 12:57 UTC, CherniyKot commented on Roguelike/World/Providers/Generator/Dungeons/CellHelpers.cs
> +        for (var y = 0; y < template.GetLength(1); y++)
райдер хочет так их ставить при форматировании((

2023-07-19 18:22 UTC, merged