Задание №4: Улучшение поведения мобов и управления игрока
PinochetLab/RoguelikeGame pull request #17
Opened 2023-06-11 19:59 UTC by EnergyNick

2023-06-17 11:35 UTC, yurii-litvinov requested changes
Собственно тестировал в рантайме только на этом пуллреквесте, вот комментарии:
- Было бы неплохо сделать какой-нибудь выбор карты, потому как сейчас карта, как я понял, всегда генерится, одним генератором
- Было бы неплохо делать что-то по факту безвременной кончины персонажа, иначе игра — это философская притча о том, что жизнь идёт дальше и всё такое :)
- Всё-таки нет документации и юнит-тестов, поэтому минус сколько-то баллов к каждой домашке (восстановимых, если без них на хорошую оценку не хватит)
- По условию хотели ещё трусливых мобов, которые активно убегают от персонажа
- Экспа и уровни вроде не работают, хотя в UI есть
- Конфузия есть в отдельном пуллреквесте, а тут нету

2023-06-17 11:35 UTC, yurii-litvinov commented on Roguelike/Actors/Enemies/AI/StateMachine/MachineQueueExtensions.cs
> +    /// <summary>
```suggestion
    }
    
    /// <summary>
```

2023-06-17 11:35 UTC, yurii-litvinov commented on Roguelike/Actors/Enemies/AI/StateMachine/StateBehaviour.cs
> +public sealed class StateBehaviour<T>
Это, как я понял, портированные куски кода из FSMSharp? Чего вы её не подключили как сабмодуль, если она через NuGet не поставляется? Так, получается, вы её берёте на сопровождение и должны за неё отвечать

2023-06-17 11:35 UTC, yurii-litvinov commented on Roguelike/Actors/Enemies/AI/StateMachine/StateMachine.cs
> +
Где-то нет пустых строк, где-то по две

2023-06-25 12:51 UTC, CherniyKot commented
Пофиксил экспу и уровни, доделал конфузию, добавил геймовер и рестарт

2023-06-25 13:12 UTC, CherniyKot commented
Сделал курицу используемым предметом

2023-06-25 15:42 UTC, yurii-litvinov requested changes
Стало лучше, но довольно много можно заработать за юнит-тесты и техническую документацию (диздок, который отражает последнюю версию кода, если успеете)

2023-06-25 15:42 UTC, yurii-litvinov commented on Roguelike/Actors/Enemies/AI/Behaviour/AggressiveBehaviour.cs
> +///     Агрессивное поведение - атакует и преследует игрока если видит
Тут обычно отступ не ставится

2023-06-25 15:42 UTC, yurii-litvinov commented on Roguelike/Actors/Enemies/AI/Behaviour/ConfusedBehaviour.cs
> +/// <summary>
А вот тут ставится пустая строчка. До начала комментария к классу — вроде как всегда.

2023-06-25 15:42 UTC, yurii-litvinov commented on Roguelike/Actors/Enemies/AI/Behaviour/PathFinder.cs
> +    /// <summary>
Ну и между членом класса и комментарием к следующему ставится пустая строчка

2023-06-25 15:42 UTC, yurii-litvinov commented on Roguelike/Actors/Enemies/Enemy.cs
> +///     Данный класс отвечает абстрактного врага
```suggestion
///     Данный класс отвечает за абстрактного врага
```

2023-06-25 15:42 UTC, yurii-litvinov commented on Roguelike/Actors/Enemies/Froggy.cs
> +            });
Вообще, не хотелось бы, чтобы этим конкретные мобы занимались. Машина состояний по идее у них общая (по крайней мере, общие состояния точно есть), так что можно её абстрагировать, а из мобов просто на неё ссылаться.

2023-06-25 15:42 UTC, yurii-litvinov commented on Roguelike/Actors/Hero/WeaponSlot.cs
> +///     Данный класс отвечает за отображение ткущего предмета на игроке
```suggestion
///     Данный класс отвечает за отображение текущего предмета на игроке
```

2023-06-25 15:42 UTC, yurii-litvinov commented on Roguelike/Actors/InventoryUtils/Items/GenericBowItem.cs
>      public override string Name => "Great sword";
?

2023-06-25 15:42 UTC, yurii-litvinov commented on Roguelike/Actors/InventoryUtils/Items/OneUseItem.cs
> +public abstract class OneUseItem : WeaponItem
Кстати, после использования спрайт вещи на спрайте персонажа остаётся.

2023-06-25 15:42 UTC, yurii-litvinov commented on Roguelike/Actors/InventoryUtils/Items/WeaponItem.cs
> +///     Данный класс отвечает за предметы являющиеся оружием (активные предметы).
```suggestion
///     Данный класс отвечает за предметы, являющиеся оружием (активные предметы).
```

2023-06-25 15:42 UTC, yurii-litvinov commented on Roguelike/Components/Health/HealthComponent.cs
> +    ///     Вызывается если здоровья достигает нуля
```suggestion
    ///     Вызывается, если здоровье достигает нуля
```

2023-07-19 18:22 UTC, merged