Задание №1: Основы рогалика
PinochetLab/RoguelikeGame pull request #9
Opened 2023-06-10 15:37 UTC by EnergyNick

2023-06-10 19:54 UTC, yurii-litvinov requested changes
Определённо не хватает:
- тестов
- значительной части комментариев
- инструкции по сборке и запуску в README
- лицензии

Ещё из функциональных требований нет генерации карты и загрузки из файла. Зато есть моб и боёвка, это уже небольшой балл за вторую часть.

2023-06-10 19:54 UTC, yurii-litvinov commented on Roguelike/Actors/AI/Enemy.cs
> +﻿using System;
Тут и везде много лишних using-ов

2023-06-10 19:54 UTC, yurii-litvinov commented on Roguelike/Actors/AI/Enemy.cs
> +public class Enemy : Actor, IDamageable, IActorCreatable<Enemy>
```suggestion
namespace Roguelike.Actors.AI;

public class Enemy : Actor, IDamageable, IActorCreatable<Enemy>
```

2023-06-10 19:54 UTC, yurii-litvinov commented on Roguelike/Actors/AI/Enemy.cs
> +    private int t = 0;
```suggestion
    }

    private int t = 0;
```

2023-06-10 19:54 UTC, yurii-litvinov commented on Roguelike/Actors/AI/Enemy.cs
> +    private int t = 0;
И это не лучшее имя поля

2023-06-10 19:54 UTC, yurii-litvinov commented on Roguelike/Actors/AI/PathFinder.cs
> +public class Cell
Это какое-то ограничение библиотеки, что Cell должен быть обязательно не вложенным классом, иметь кучу public-полей и не быть record-ом?

2023-06-10 19:54 UTC, yurii-litvinov commented on Roguelike/Actors/Actor.cs
> +    public virtual string Tag => "none";
Тэги типов в ООП вообще не очень. Может быть идеологически более правильно заменить if-ы, которые проверяют тэги, на виртуальные методы, и для разных классов объектов реализовывать их или нет (или реализовывать по-разному). То, что лягушка не может поднять KFC, правильнее делать не проверкой в коллайдере KFC, не игрок ли на него наступил, а вызовом метода GetKfc, который для лягушки пустой. Иное дело, что с тэгами может быть проще и меньше кода.

2023-06-10 19:54 UTC, yurii-litvinov commented on Roguelike/Actors/Actor.cs
> +    public TComp AddComponent<TComp>() where TComp : Component, new()
Лучше TComponent, не сокращайте имена

2023-06-10 19:54 UTC, yurii-litvinov commented on Roguelike/Actors/Hero/Hero.cs
> +        }
Тоже кажется, что недоиспользованный полиморфизм какой-то

2023-06-10 19:54 UTC, yurii-litvinov commented on Roguelike/Actors/InventoryUtils/Items/Bow1Item.cs
> +    public override bool IsSword => false;
А если у вас будет 150 видов оружия? :)

2023-06-10 19:54 UTC, yurii-litvinov commented on Roguelike/Core/BaseWorldComponent.cs
> +    /// Метод, который вызывается при совершении главным героем хода. Двигает все подвижные игровые объекты.
Лягушка ходит и без персонажа, а вот стрела без персонажа не летает (интересно, можно ли это использовать, "заминировав" проход висящей стрелой, чтобы лягушка на неё напоролась? Проверить сходу не получилось, потому что лягушка вообще только раза три потеряла здоровье от стрелы из многих попыток).

2023-06-10 19:54 UTC, yurii-litvinov commented on Roguelike/World/WorldComponent.cs
> +        CreateActor<Wall>(4, 4);
Выглядит стрёмно :) Можно было грузить из файла или хотя бы это синтаксически более симпатично записать (паттерн "Builder"?)

2023-06-11 14:50 UTC, CherniyKot commented
@yurii-litvinov, лишние юзинги убрали и оружие полностью переработали во 2 ПР, там же заглушку поведения мобов заменили на нормальную логику, странные имена переменных исчезли)

2023-07-19 18:21 UTC, merged